server:
  port: 8072
spring:
  application:
    name: student-management
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/students
    username: postgres
    password: BigMitch@123
    schema:
      initial-catalog: user_accounts
      create-if-not-exists: true
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    config:
      allow-override: true
